name: gojs
description: A Dart interface for GoJS
version: 1.0.0
homepage: https://github.com/jodinathan/gojs_dart
environment:
  sdk: '>= 2.6.0 < 3.0.0'

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  