name: gojs
description: A Dart interface for GoJS. A Web Framework for rapidly building interactive diagrams
version: 2.0.0
homepage: https://github.com/jodinathan/gojs_dart
environment:
  sdk: '>=2.12.2<3.0.0'

dependencies:
  js: ^0.6.3

