name: gojs_flowchart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1+1
  #gojs: any
  gojs:
    path: '../../'

dev_dependencies:
  build_runner: ^1.7.3
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
