name: gojs_flowchart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  js: ^0.6.3
  #gojs: any
  gojs:
    path: '../../'

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.1
